Categories = dict(PENDING=0, UNKNOWN=1, FRIEND=2, NEUTRAL=3, HOSTILE=4, ASSUMED_FRIEND=5, ASSUMED_HOSTILE=6,
                  UNCERTAIN_FRIEND=7, UNCERTAIN_HOSTILE=8)
Colours = dict(GRAY=0, GREEN=1, BLUE=2, PURPLE=3, YELLOW=4, RED=5, C_GREEN=6, C_RED=7)
